In [1]:
from data_preprocess import *

In [2]:
import pprint 
pp = pprint.PrettyPrinter(indent=4)

In [3]:
test_cases = [
#     'pglib_opf_case24_ieee_rts.m',
#     'pglib_opf_case30_ieee.m',
#     'pglib_opf_case57_ieee.m',
#     'pglib_opf_case73_ieee_rts.m',
#     'pglib_opf_case89_pegase.m',
#     'pglib_opf_case118_ieee.m',
#     'pglib_opf_case179_goc.m',
#     'pglib_opf_case162_ieee_dtc.m',
#     'pglib_opf_case200_tamu.m',
#     'pglib_opf_case240_pserc.m',
#     'pglib_opf_case300_ieee.m',
#     'pglib_opf_case500_tamu.m',
    
#     'pglib_opf_case588_sdet.m',
    'pglib_opf_case1354_pegase.m',
#     'pglib_opf_case1888_rte.m',
#     'pglib_opf_case1951_rte.m',
#     'pglib_opf_case2000_tamu.m'
]

## Example of parsing active constraints: DC-OPF

In [4]:
org_dir = os.getcwd()
os.chdir('./matpower7.0/')

In [5]:
eng = matlab.engine.start_matlab()

In [6]:
test_case_idx = 0
case_name = test_cases[test_case_idx]

In [7]:
data = eng.dc_opf_solver(case_name, 0.03)

In [8]:
Pg = np.squeeze(np.array(data['Pg']))
B_idx = np.squeeze(np.array(data['B_idx']))
GB_map = np.squeeze(np.array(data['GB_map'])).astype(int)
F = np.squeeze(np.array(data['F']))
Pg_lim = np.array(data['Pg_lim'])
F_lim = np.array(data['F_lim'])
w = np.squeeze(np.array(data['w']))

### Generator active constraints: [Pg_min, Pg_max]]

In [9]:
Pg

array([ 853.        ,    0.        ,  100.        ,  120.        ,
        666.67      ,    0.        ,  540.        ,  529.        ,
        -68.89      , -360.        ,    0.        ,  480.        ,
        100.        ,   80.        ,  240.        ,  120.        ,
       -148.53      ,    0.        ,    0.        , -118.93      ,
        666.67      ,  200.        ,  750.48516115, 2400.        ,
        666.67      ,  120.        ,  200.        ,  300.        ,
          0.        ,  400.        ,    0.        , -165.54      ,
       2000.        ,  400.        , -165.47      ,    0.        ,
        100.        ,  -99.74003954,    0.        ,    0.        ,
          0.        ,    0.        , 1710.        , 1000.        ,
          0.        ,    0.        , 1377.26571452,  100.        ,
         31.92      ,  100.        ,  912.78      ,   39.35      ,
         40.        , 1000.        ,  666.67      ,    0.        ,
        100.        ,  -71.05      ,    0.        ,    0.     

In [10]:
Pg_lim

array([[ 1.00000e+03,  3.33330e+02],
       [ 1.60000e+02,  0.00000e+00],
       [ 1.00000e+02, -2.07180e+02],
       [ 1.20000e+02,  0.00000e+00],
       [ 2.00000e+03,  6.66670e+02],
       [ 2.80000e+02,  0.00000e+00],
       [ 5.40000e+02,  0.00000e+00],
       [ 6.00000e+02,  2.00000e+02],
       [ 1.00000e+02, -6.88900e+01],
       [ 1.00000e+02, -3.60000e+02],
       [ 4.00000e+01,  0.00000e+00],
       [ 4.80000e+02,  1.60000e+02],
       [ 1.00000e+02, -6.16000e+01],
       [ 8.00000e+01,  0.00000e+00],
       [ 2.40000e+02,  0.00000e+00],
       [ 1.20000e+02,  0.00000e+00],
       [ 1.00000e+02, -1.48530e+02],
       [ 3.35800e+01,  0.00000e+00],
       [ 8.00000e+01,  0.00000e+00],
       [ 1.00000e+02, -1.18930e+02],
       [ 2.00000e+03,  6.66670e+02],
       [ 2.00000e+02,  0.00000e+00],
       [ 1.00000e+03,  3.33330e+02],
       [ 2.40000e+03,  8.00000e+02],
       [ 2.00000e+03,  6.66670e+02],
       [ 1.20000e+02,  0.00000e+00],
       [ 2.00000e+02,  0.00000e+00],
 

In [11]:
Pg_active = get_Pg_active_constraints(Pg, Pg_lim)
Pg_active

array([0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1.

### Bus active constraints, due to precense of co-related generation: [Pb_min, Pb_max]

In [12]:
Pb = get_Pb(Pg, GB_map)
Pb

{124: 852.999999999997,
 150: 0.0,
 221: 100.0,
 338: 120.0,
 352: 666.67,
 413: 0.0,
 453: 540.0,
 516: 529.0,
 564: -68.89,
 583: -360.0,
 615: 0.0,
 616: 480.0,
 639: 100.0,
 682: 80.0,
 749: 240.0,
 757: 120.0,
 776: -148.53,
 778: 0.0,
 795: 0.0,
 803: -118.92999999999998,
 823: 666.67,
 851: 200.0,
 858: 750.4851611536528,
 891: 2400.0,
 972: 666.6700000000001,
 1001: 120.0,
 1002: 200.0,
 1043: 300.0,
 1083: 0.0,
 1093: 400.0,
 1100: 0.0,
 1102: -165.54,
 1237: 2000.0,
 1251: 400.0,
 1295: -165.47,
 1341: 0.0,
 1354: 100.0,
 1422: -99.74003953843238,
 1436: 0.0,
 1478: 0.0,
 1604: 0.0,
 1642: 0.0,
 1680: 1709.9999999999677,
 1708: 1000.0,
 1721: 0.0,
 1754: 0.0,
 1794: 1377.265714522769,
 1808: 100.0,
 1851: 31.920000000000005,
 1852: 100.0,
 1888: 912.7799999999999,
 1914: 39.35,
 1959: 40.00000000000001,
 2035: 1000.0,
 2050: 666.67,
 2085: 0.0,
 2177: 100.0,
 2197: -71.05,
 2276: 0.0,
 2291: 0.0,
 2359: 0.0,
 2421: 100.0,
 2425: -134.0,
 2426: -57.60000000000001,
 2446: 2000.

In [13]:
Pb_lim = get_Pb_lim(Pg_lim, GB_map)
Pb_lim

{124: array([1000.  ,  333.33]),
 150: array([160.,   0.]),
 221: array([ 100.  , -207.18]),
 338: array([120.,   0.]),
 352: array([2000.  ,  666.67]),
 413: array([280.,   0.]),
 453: array([540.,   0.]),
 516: array([600., 200.]),
 564: array([100.  , -68.89]),
 583: array([ 100., -360.]),
 615: array([40.,  0.]),
 616: array([480., 160.]),
 639: array([100. , -61.6]),
 682: array([80.,  0.]),
 749: array([240.,   0.]),
 757: array([120.,   0.]),
 776: array([ 100.  , -148.53]),
 778: array([33.58,  0.  ]),
 795: array([80.,  0.]),
 803: array([ 100.  , -118.93]),
 823: array([2000.  ,  666.67]),
 851: array([200.,   0.]),
 858: array([1000.  ,  333.33]),
 891: array([2400.,  800.]),
 972: array([2000.  ,  666.67]),
 1001: array([120.,   0.]),
 1002: array([200.,   0.]),
 1043: array([900., 300.]),
 1083: array([120.,   0.]),
 1093: array([1200.,  400.]),
 1100: array([80.,  0.]),
 1102: array([ 100.  , -165.54]),
 1237: array([2000.  ,  666.67]),
 1251: array([1200.,  400.]),
 1295

In [14]:
Pb_active = get_Pb_active_constraints(Pg, Pg_lim, GB_map)
Pb_active

array([0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1.

### Flow Constraints: [-F_max, F_max] 

In [15]:
F

array([-6.19960756e+01, -2.61643494e+01, -1.42108547e-12, ...,
        2.83180736e+02,  2.90664750e+02,  3.47989032e+02])

In [16]:
F_lim

array([[39412.],
       [  319.],
       [ 7252.],
       ...,
       [  591.],
       [  591.],
       [  591.]])

In [17]:
F_active = get_F_active_constraints(F, F_lim)
F_active

array([0, 0, 0, ..., 0, 0, 0])

### Merge all active constriants

In [18]:
active_aconstraints = merge_active_constraints(Pg_active, Pb_active, F_active)
active_aconstraints

array([0., 1., 1., ..., 0., 0., 0.])

## (Optional) Example of parsing active constraints: AC-OPF

In [19]:
data = eng.ac_opf_solver(case_name, 0.03)

In [20]:
pp.pprint(data)

{   'B_idx': matlab.double([[3.0],[4.0],[10.0],[21.0],[22.0],[26.0],[29.0],[44.0],[53.0],[58.0],[59.0],[90.0],[96.0],[113.0],[115.0],[118.0],[124.0],[128.0],[145.0],[148.0],[150.0],[163.0],[171.0],[174.0],[184.0],[188.0],[195.0],[196.0],[198.0],[207.0],[216.0],[217.0],[218.0],[221.0],[225.0],[280.0],[283.0],[292.0],[305.0],[306.0],[314.0],[333.0],[338.0],[346.0],[350.0],[352.0],[367.0],[401.0],[408.0],[410.0],[413.0],[416.0],[426.0],[432.0],[444.0],[449.0],[453.0],[455.0],[490.0],[500.0],[502.0],[506.0],[513.0],[516.0],[520.0],[549.0],[554.0],[556.0],[561.0],[564.0],[575.0],[583.0],[594.0],[601.0],[604.0],[608.0],[609.0],[615.0],[616.0],[619.0],[639.0],[641.0],[658.0],[661.0],[666.0],[678.0],[682.0],[687.0],[707.0],[718.0],[720.0],[726.0],[742.0],[747.0],[749.0],[750.0],[757.0],[766.0],[769.0],[772.0],[776.0],[778.0],[789.0],[795.0],[800.0],[803.0],[804.0],[805.0],[809.0],[819.0],[823.0],[839.0],[851.0],[858.0],[870.0],[871.0],[883.0],[891.0],[892.0],[900.0],[903.0],[905.0],[907.0],[90

In [21]:
eng.quit()

In [22]:
os.chdir(org_dir)

## Create Datasets for NNs

### example of creating a dataset
- **x**: uncertainty realization as a feature input
- **y**: active constraints index as a label output

In [23]:
dataset = create_dataset(case_name, dataset_size=1)
dataset

> creating dataset with pglib_opf_case1354_pegase.m


100%|██████████| 1/1 [00:01<00:00,  1.97s/it]


{'x': array([ -1.16583003,   3.85436924,  -2.29447252, ...,  -0.03867129,
        -11.97397703,   0.        ]),
 'y': array([[0., 1., 1., ..., 0., 0., 0.]])}

### Build datasets

In [24]:
# dataset_size = 2
dataset_size = 50000

In [ ]:
build_datasets(test_cases, dataset_size)

> creating dataset with pglib_opf_case1354_pegase.m


  3%|▎         | 1726/50000 [1:11:04<89:00:41,  6.64s/it]

### Check datasets

In [ ]:
infile = open('./datasets/pglib_opf_case24_ieee_rts.pickle','rb')
dataset = pickle.load(infile)
infile.close()

In [ ]:
dataset