In [1]:
from data_preprocess import *

In [2]:
import pprint 
pp = pprint.PrettyPrinter(indent=4)

In [3]:
test_cases = [
    'pglib_opf_case24_ieee_rts.m', 
    'pglib_opf_case73_ieee_rts.m',
    'pglib_opf_case162_ieee_dtc.m',
    'pglib_opf_case300_ieee.m',
]

## Example of parsing active constraints: DC-OPF

In [7]:
org_dir = os.getcwd()
os.chdir('./matpower7.0/')

In [8]:
eng = matlab.engine.start_matlab()

In [9]:
test_case_idx = 0
case_name = test_cases[test_case_idx]

In [10]:
data = eng.dc_opf_solver(case_name, 0.03)

In [11]:
Pg = np.squeeze(np.array(data['Pg']))
B_idx = np.squeeze(np.array(data['B_idx']))
GB_map = np.squeeze(np.array(data['GB_map'])).astype(int)
F = np.squeeze(np.array(data['F']))
Pg_lim = np.array(data['Pg_lim'])
F_lim = np.array(data['F_lim'])
w = np.squeeze(np.array(data['w']))

### Generator active constraints: [Pg_min, Pg_max]]

In [12]:
Pg

array([ 16.        ,  16.        ,  76.        ,  76.        ,
        16.        ,  16.        ,  76.        ,  76.        ,
        42.06152311,  42.06152311,  42.06152311,  69.        ,
        69.        ,  69.        ,   0.        ,   2.4       ,
         2.4       ,   2.4       ,   2.4       ,   2.4       ,
       155.        , 155.        , 400.        , 400.        ,
        50.        ,  50.        ,  50.        ,  50.        ,
        50.        ,  50.        , 155.        , 155.        ,
       350.        ])

In [13]:
Pg_lim

array([[ 20. ,  16. ],
       [ 20. ,  16. ],
       [ 76. ,  15.2],
       [ 76. ,  15.2],
       [ 20. ,  16. ],
       [ 20. ,  16. ],
       [ 76. ,  15.2],
       [ 76. ,  15.2],
       [100. ,  25. ],
       [100. ,  25. ],
       [100. ,  25. ],
       [197. ,  69. ],
       [197. ,  69. ],
       [197. ,  69. ],
       [  0. ,   0. ],
       [ 12. ,   2.4],
       [ 12. ,   2.4],
       [ 12. ,   2.4],
       [ 12. ,   2.4],
       [ 12. ,   2.4],
       [155. ,  54.3],
       [155. ,  54.3],
       [400. , 100. ],
       [400. , 100. ],
       [ 50. ,  10. ],
       [ 50. ,  10. ],
       [ 50. ,  10. ],
       [ 50. ,  10. ],
       [ 50. ,  10. ],
       [ 50. ,  10. ],
       [155. ,  54.3],
       [155. ,  54.3],
       [350. , 140. ]])

In [14]:
Pg_active = get_Pg_active_constraints(Pg, Pg_lim)
Pg_active

array([1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Bus active constraints, due to precense of co-related generation: [Pb_min, Pb_max]

In [15]:
Pb = get_Pb(Pg, GB_map)
Pb

{1: 184.0,
 2: 184.0,
 7: 126.1845693377164,
 13: 207.00000000001955,
 14: 0.0,
 15: 167.0,
 16: 155.0,
 18: 400.0,
 21: 400.0,
 22: 300.0,
 23: 660.0}

In [16]:
Pb_lim = get_Pb_lim(Pg_lim, GB_map)
Pb_lim

{1: array([192. ,  62.4]),
 2: array([192. ,  62.4]),
 7: array([300.,  75.]),
 13: array([591., 207.]),
 14: array([0., 0.]),
 15: array([215. ,  66.3]),
 16: array([155. ,  54.3]),
 18: array([400., 100.]),
 21: array([400., 100.]),
 22: array([300.,  60.]),
 23: array([660. , 248.6])}

In [17]:
Pb_active = get_Pb_active_constraints(Pg, Pg_lim, GB_map)
Pb_active

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

### Flow Constraints: [-F_max, F_max] 

In [18]:
F

array([   9.01807878,   -2.8249142 ,   71.54887695,   43.61314964,
         57.74153453,   27.6901447 , -222.71283194,  -28.47282559,
          1.22784691,  -83.59383372,   -0.44140075,  -95.30762768,
        -74.37610955, -119.27959575, -133.02412889, -160.83080313,
       -174.7100866 ,  -97.62174494, -182.48865394,  -72.66877603,
       -235.06543946, -222.52355738, -376.8556333 ,   86.97128895,
       -226.44345794, -226.44345794,  222.71283194, -328.99516323,
         93.49592069, -187.92434861, -141.07081462,  -53.02113475,
        -53.02113475,  -39.92651101,  -39.92651101, -101.20550158,
       -101.20550158, -158.92918538])

In [19]:
F_lim

array([[175.],
       [175.],
       [175.],
       [175.],
       [175.],
       [175.],
       [400.],
       [175.],
       [175.],
       [175.],
       [175.],
       [175.],
       [175.],
       [400.],
       [400.],
       [400.],
       [400.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.],
       [500.]])

In [20]:
F_active = get_F_active_constraints(F, F_lim)
F_active

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Merge all active constriants

In [21]:
active_aconstraints = merge_active_constraints(Pg_active, Pb_active, F_active)
active_aconstraints

array([1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## (Optional) Example of parsing active constraints: AC-OPF

In [22]:
data = eng.ac_opf_solver(case_name, 0.03)

In [23]:
pp.pprint(data)

{   'B_idx': matlab.double([[1.0],[2.0],[3.0],[4.0],[5.0],[6.0],[7.0],[8.0],[9.0],[10.0],[11.0],[12.0],[13.0],[14.0],[15.0],[16.0],[17.0],[18.0],[19.0],[20.0],[21.0],[22.0],[23.0],[24.0]]),
    'F': matlab.double([[10.73631016164547],[-1.4541207927666528],[68.30182019291729],[45.57878467748592],[55.16565170032875],[24.859935489397582],[-202.53647364926962],[-29.786113920714953],[-2.99746750354297],[-85.42558991117156],[89.95828467161655],[-51.33936811722335],[-36.88505416882393],[-111.82296428246727],[-126.64974631905284],[-155.83522261316324],[-170.88489039007874],[-104.75824954533881],[-163.74412699562777],[-77.4590163854252],[-221.11105436421133],[-208.6722953427937],[-363.5356595109862],[91.23386608870629],[-217.25907675385548],[-217.25907675385548],[206.31584923453303],[-316.27244032893447],[87.3743830212644],[-180.5095075802409],[-138.8367631946502],[-58.22842417958005],[-58.22842417958005],[-46.053691937745285],[-46.053691937745285],[-109.55531869913067],[-109.55531869913067],[-

In [24]:
eng.quit()

In [25]:
os.chdir(org_dir)

## Create Datasets for NNs

### example of creating a dataset
- **x**: uncertainty realization as a feature input
- **y**: active constraints index as a label output

In [26]:
dataset = create_dataset(case_name, dataset_size=1)
dataset

> creating dataset with pglib_opf_case24_ieee_rts.m


100%|██████████| 1/1 [00:00<00:00,  3.44it/s]


{'x': array([ 1.58401582,  3.01095666,  3.92517972, -0.67363885,  0.62594622,
        -3.21211384,  3.33148362, -5.88446965, -5.61156991, -4.73556736,
         0.        ,  0.        ,  2.58526479, -4.39368282, 13.03153912,
        -5.13454926,  0.        , -2.41205595,  1.73329259,  1.20137701,
         0.        ,  0.        ,  0.        ,  0.        ]),
 'y': array([[1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]])}

### Build datasets

In [28]:
# dataset_size = 2
dataset_size = 50000

In [27]:
build_datasets(test_cases, dataset_size)

> creating dataset with pglib_opf_case162_ieee_dtc.m


100%|██████████| 50000/50000 [3:14:59<00:00,  4.27it/s]  


> creating dataset with pglib_opf_case300_ieee.m


100%|██████████| 50000/50000 [4:52:27<00:00,  2.85it/s]  


### Check datasets

In [29]:
infile = open('./datasets/pglib_opf_case24_ieee_rts.pickle','rb')
dataset = pickle.load(infile)
infile.close()

In [30]:
dataset

{'x': array([[ 1.58401582,  3.01095666,  3.92517972, ...,  0.        ,
          0.        ,  0.        ],
        [ 3.54218077,  3.2279853 , -4.66372524, ...,  0.        ,
          0.        ,  0.        ],
        [-0.62343597,  2.58585634, -4.13018588, ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [-1.73786221, -1.83840692,  6.28492785, ...,  0.        ,
          0.        ,  0.        ],
        [-2.94739091, -1.37913875, -7.33716418, ...,  0.        ,
          0.        ,  0.        ],
        [-1.56552295,  3.44187377,  8.9611732 , ...,  0.        ,
          0.        ,  0.        ]]),
 'y': array([[1., 1., 1., ..., 0., 0., 0.],
        [1., 1., 1., ..., 0., 0., 0.],
        [1., 1., 1., ..., 0., 0., 0.],
        ...,
        [1., 1., 1., ..., 0., 0., 0.],
        [1., 1., 1., ..., 0., 0., 0.],
        [1., 1., 1., ..., 0., 0., 0.]])}